"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
[](#acc7ff)$directory[](#acc7ff) """

right_format = """$character [](fg:#ddbcdf)$cmd_duration[](fg:#ddbcdf)"""

[cmd_duration]
min_time = 0
format = "[$duration](bg:#ddbcdf fg:#3f2844)"

[character]
format = "$symbol"
success_symbol = ""
error_symbol = "[](fg:#ffb4ab)[](fg:#ffb4ab)"



[fill]
symbol = ''
style = 'bold fg:#acc7ff'

[directory]
style = "bg:#acc7ff fg:#0e2f60"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
