"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
[](#88d6ba)$directory[](#88d6ba) """

right_format = """$character [](fg:#a8cbe1)$cmd_duration[](fg:#a8cbe1)"""

[cmd_duration]
min_time = 0
format = "[$duration](bg:#a8cbe1 fg:#0c3446)"

[character]
format = "$symbol"
success_symbol = ""
error_symbol = "[](fg:#ffb4ab)[](fg:#ffb4ab)"



[fill]
symbol = ''
style = 'bold fg:#88d6ba'

[directory]
style = "bg:#88d6ba fg:#00382a"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
