"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
[](#ffb2b9)$directory[](#ffb2b9) """

right_format = """$character [](fg:#e8c08e)$cmd_duration[](fg:#e8c08e)"""

[cmd_duration]
min_time = 0
format = "[$duration](bg:#e8c08e fg:#442b06)"

[character]
format = "$symbol"
success_symbol = ""
error_symbol = "[](fg:#ffb4ab)[](fg:#ffb4ab)"



[fill]
symbol = ''
style = 'bold fg:#ffb2b9'

[directory]
style = "bg:#ffb2b9 fg:#561d26"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
